# Generated by Django 5.1.7 on 2025-03-07 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
                ('short_designation', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['designation'],
            },
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['bank_name', 'name']},
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(default='', help_text='Name of the bank', max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('JPY', 'Japanese Yen (¥)'), ('CHF', 'Swiss Franc (Fr)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('XPF', 'CFP Franc (₣)'), ('CNY', 'Chinese Yuan (¥)')], default='EUR', help_text='Three-letter currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(help_text='Name of the account', max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.accounttype'),
        ),
    ]
