# Generated by Django 5.1.7 on 2025-03-07 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accounttype_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='reference',
            field=models.CharField(blank=True, help_text='Auto-generated reference code', max_length=100),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation date and time'),
        ),
    ]
