# Generated by Django 5.1.7 on 2025-03-08 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_paymentmethod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='is_system',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='tax_household',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this payment method is active'),
        ),
    ]
