# Generated by Django 5.1.7 on 2025-03-08 01:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_paymentmethod_is_system_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current balance of the account', max_digits=12),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='balance_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date when the balance was last updated'),
        ),
    ]
