# Generated by Django 5.1.7 on 2025-03-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_simple_transaction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Cost center name', max_length=100)),
                ('color', models.CharField(default='#7295d8', help_text='Color code for the cost center (hex format)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_household', models.ForeignKey(help_text='The tax household this cost center belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='core.taxhousehold')),
            ],
            options={
                'verbose_name': 'Cost Center',
                'verbose_name_plural': 'Cost Centers',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transactioncategory',
            name='cost_center',
            field=models.ForeignKey(blank=True, help_text='The cost center this category belongs to (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='core.costcenter'),
        ),
    ]
