# Generated by Django 5.1.7 on 2025-03-08 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_cost_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the transaction')),
                ('description', models.CharField(help_text='Description of the transaction', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of the transaction', max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring transaction')),
                ('is_family_transaction', models.BooleanField(default=False, help_text='Whether this transaction is for the whole family')),
                ('transaction_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], default='expense', help_text='Type of transaction (expense or income)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(help_text='Account used for the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.bankaccount')),
                ('category', models.ForeignKey(help_text='Category of the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.transactioncategory')),
                ('payment_method', models.ForeignKey(help_text='Payment method used for the transaction', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.paymentmethod')),
                ('recipient', models.ForeignKey(blank=True, help_text='Recipient of the transaction', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='core.householdmember')),
                ('tax_household', models.ForeignKey(help_text='The tax household this transaction belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.taxhousehold')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
