# Generated by Django 5.1.7 on 2025-03-08 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transaction_model_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_family_recipient',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='recipient',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_member',
            field=models.ForeignKey(blank=True, help_text="Specific household member when recipient_type is 'member'", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='core.householdmember'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient_type',
            field=models.CharField(choices=[('family', 'Family'), ('member', 'Household Member'), ('external', 'External')], default='external', help_text='Type of recipient', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='recurrence_period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], default='', help_text='Frequency of recurrence for recurring transactions', max_length=10),
        ),
    ]
