# Generated by Django 5.1.7 on 2025-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_transaction_is_family_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='End date for recurring transactions (defaults to one year after start date)', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurrence_start_date',
            field=models.DateField(blank=True, help_text='Start date for recurring transactions', null=True),
        ),
    ]
