# Generated by Django 5.1.7 on 2025-03-09 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_transaction_recurrence_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Indicates if this transaction is part of a transfer between accounts'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='paired_transaction',
            field=models.ForeignKey(blank=True, help_text='For transfers, links to the paired transaction (source to destination or vice versa)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_paired_transaction', to='core.transaction'),
        ),
    ]
